controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

imu_sensor_broadcaster:
    ros__parameters:
      sensor_name: "imu_sensor"
      frame_id: imu_link
      orientation_covariance: [0.0025, 0.0, 0.0, 0.0, 0.0025, 0.0, 0.0, 0.0, 0.0025]
      angular_velocity_covariance: [0.02, 0.0, 0.0, 0.0, 0.02, 0.0, 0.0, 0.0, 0.02]
      linear_acceleration_covariance: [0.04, 0.0, 0.0, 0.0, 0.04, 0.0, 0.0, 0.0, 0.04]
      publish_rate: 50.0

      interface_names.orientation.x: "imu_sensor/orientation.x"
      interface_names.orientation.y: "imu_sensor/orientation.y"
      interface_names.orientation.z: "imu_sensor/orientation.z"
      interface_names.orientation.w: "imu_sensor/orientation.w"

      interface_names.angular_velocity.x: "imu_sensor/angular_velocity.x"
      interface_names.angular_velocity.y: "imu_sensor/angular_velocity.y"
      interface_names.angular_velocity.z: "imu_sensor/angular_velocity.z"

      interface_names.linear_acceleration.x: "imu_sensor/linear_acceleration.x"
      interface_names.linear_acceleration.y: "imu_sensor/linear_acceleration.y"
      interface_names.linear_acceleration.z: "imu_sensor/linear_acceleration.z"



