controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    diffbot_base_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    position_controller:
      type: position_controllers/JointGroupPositionController

diffbot_base_controller:
  ros__parameters:
    enable_odom_tf: false # <<===== if true, Publish odometry transform between 'odom' ==> 'base_link'  (odom_frame_id and base_frame_id)
    odom_frame_id: odom
    base_frame_id: base_footprint    ###  base_link

    tf_frame_prefix_enable: false
    tf_frame_prefix: ""

    left_wheel_names: [ "left_wheel_joint" ]
    right_wheel_names: [ "right_wheel_joint" ]

    wheel_separation: 0.3
    wheel_radius: 0.048

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0 ## Hz    (for odometry msg and tf)

    pose_covariance_diagonal: [ 0.001, 0.001, 0.001, 0.001, 0.001, 0.01 ]
    twist_covariance_diagonal: [ 0.001, 0.001, 0.001, 0.001, 0.001, 0.01 ]

    open_loop: false # false = Calculate odometry from encoder ticks

    cmd_vel_timeout: 0.2
    publish_limited_velocity: false
    use_stamped_vel: true
    velocity_rolling_window_size: 10 ## 10 is the default value

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    # value of .NAN will de-activate the limit
    linear:
      x:
        max_velocity: .nan  # 4.0
        max_acceleration: .nan  # 0.1
        min_acceleration: .nan  # -0.5
        max_jerk: .nan

    angular:
      z:
        max_velocity:  .nan  # 0.4
        max_acceleration: .nan  # 1.0
        max_jerk: .nan

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: "imu_sensor"
    frame_id: "imu_link"
    static_covariance_orientation: [ 0.0025, 0.001, 0.001, 0.001, 0.0025, 0.001, 0.001, 0.001, 0.0025 ]
    static_covariance_angular_velocity: [ 0.02, 0.0, 0.0, 0.0, 0.02, 0.0, 0.0, 0.0, 0.02 ]
    static_covariance_linear_acceleration: [ 0.04, 0.0, 0.0, 0.0, 0.04, 0.0, 0.0, 0.0, 0.04 ]
    publish_rate: 30.0

joint_state_broadcaster:
  ros__parameters:
    # # # joints:
    # # # - left_wheel_joint
    # # # - right_wheel_joint
    # # # - camera_L_pan_joint
    # # # - camera_L_tilt_joint
    # # # - camera_R_pan_joint
    # # # - camera_R_tilt_joint
    # # # interfaces:
    # # #   - position
    # # #   - velocity

    publish_rate: 50.0
    use_stamped_joint_state: true
    use_stamped_transform: true

position_controller:
  ros__parameters:
    update_rate: 50 # Hz
    joints:
    - camera_L_pan_joint
    - camera_L_tilt_joint
    - camera_R_pan_joint
    - camera_R_tilt_joint
    interface_name: position
