fuse_state_estimator_node:
  ros__parameters:
    # Fixed-lag smoother configuration
    ### see: https://github.com/locusrobotics/fuse/issues/179
    ### see: https://github.com/locusrobotics/fuse/issues/223

    optimization_frequency: 10.0
    transaction_timeout: 0.05
    lag_duration: 0.5

    motion_models:
      unicycle_motion_model:
        type: fuse_models::Unicycle2D

    unicycle_motion_model:
      #                         x      y      yaw    vx     vy     vyaw   ax   ay
      process_noise_diagonal: [ 0.100, 0.100, 0.100, 0.100, 0.100, 0.100, 0.1, 0.1 ]

    sensor_models:
      initial_localization_sensor:
        type: fuse_models::Unicycle2DIgnition
        motion_models: [ unicycle_motion_model ]
        ignition: true
      odometry_sensor:
        type: fuse_models::Odometry2D
        motion_models: [ unicycle_motion_model ]
      imu_sensor:
        type: fuse_models::Imu2D
        motion_models: [ unicycle_motion_model ]

    initial_localization_sensor:
      publish_on_startup: true
      #                x      y      yaw    vx     vy     vyaw    ax     ay
      initial_state: [ 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000 ]
      initial_sigma: [ 0.100, 0.100, 0.100, 0.100, 0.100, 0.100, 0.100, 0.100 ]

    odometry_sensor:
      topic: "odom"
      linear_velocity_dimensions: [ 'x' ]
      angular_velocity_dimensions: [ 'yaw' ]
      twist_target_frame: base_footprint    ###  base_link
      position_dimensions: [ 'x', 'y' ]
      orientation_dimensions: [ 'yaw' ]
      pose_target_frame: base_footprint    ###  base_link
      use_twist_covariance: true
      differential: true
      independent: false
      tf_timeout: 0.1

    imu_sensor:
      topic: "imu"
      linear_acceleration_dimensions: [ 'x', 'y' ]
      angular_velocity_dimensions: [ 'yaw' ]
      acceleration_target_frame: base_footprint    ###  base_link
      twist_target_frame: base_footprint    ###  base_link
      orientation_dimensions: [ 'yaw' ]
      orientation_target_frame: base_footprint    ###  base_link
      differential: true
      independent: false
      tf_timeout: 0.1

    publishers:
      filtered_publisher:
        type: fuse_models::Odometry2DPublisher

    filtered_publisher:
      topic: "odom_filtered"
      base_link_frame_id: "base_footprint"    ###  base_link
      odom_frame_id: "odom"
      map_frame_id: "map"
      world_frame_id: "odom"
      publish_tf: true
      publish_frequency: 10.0
