<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="argus_camera_urdf" params="prefix y_multiplier">

    <xacro:property name="camera_height" value="0.012" />
    <xacro:property name="camera_width" value="0.041" />
    <xacro:property name="camera_length" value="0.01" />
    <xacro:property name="camera_x_offset" value="0.110" />
    <xacro:property name="camera_y_offset" value="0.03" />
    <xacro:property name="camera_z_offset" value="0.3" />
    <xacro:property name="pi_2" value="1.570796" />
    <xacro:property name="camera_mass" value="0.0001" />


    <!-- ======================================================================== -->
    <joint name="argus_camera_${prefix}_base_joint" type="fixed">
      <parent link="base_link"/>
      <child link="argus_camera_${prefix}_base_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="argus_camera_${prefix}_base_link">
      <collision>
        <origin xyz="${camera_x_offset} ${camera_y_offset * y_multiplier} ${camera_z_offset}" rpy="0 0 ${pi_2 * y_multiplier}"/>
        <geometry>
          <box size="${camera_length} ${camera_width} ${camera_height}"/>
        </geometry>
      </collision>
      <visual>
        <origin xyz="${camera_x_offset} ${camera_y_offset * y_multiplier} ${camera_z_offset}" rpy="0 0 ${pi_2 * y_multiplier}"/>
        <geometry>
          <box size="${camera_length} ${camera_width} ${camera_height/2}"/>
        </geometry>
        <material name="blue"/>
      </visual>
      <xacro:box_inertia m="${camera_mass}" w="${camera_width}" h="${camera_height}" d="${camera_length}" />
    </link>
    <!-- ======================================================================== -->

    <!-- ======================================================================== -->
    <joint name="argus_camera_${prefix}_optical_joint" type="fixed">
      <parent link="argus_camera_${prefix}_base_link"/>
      <child link="argus_camera_${prefix}_optical_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="argus_camera_${prefix}_optical_link">
      <collision>
        <origin xyz="0 0 0"/>
        <geometry>
          <box size="0.005 0.005 0.005"/>
        </geometry>
      </collision>
      <visual>
        <origin xyz="0 0 0"/>
        <geometry>
          <box size="0.005 0.005 0.005"/>
        </geometry>
        <material name="red"/>
      </visual>
      <xacro:box_inertia m="${camera_mass}" w="0.005" h="0.005" d="0.005" />
    </link>
    <!-- ======================================================================== -->

    <!-- ======================================================================== -->
    <!-- ======================================================================== -->

  </xacro:macro>

</robot>
