<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="camera_urdf" params="prefix y_multiplier">

    <xacro:property name="camera_height" value="0.016" />
    <xacro:property name="camera_width" value="0.033" />
    <xacro:property name="camera_length" value="0.033" />
    <xacro:property name="camera_x_offset" value="0.110" />
    <xacro:property name="camera_y_offset" value="0.060" />
    <xacro:property name="camera_z_offset" value="0.360" />
    <xacro:property name="pi_2" value="1.570796" />
    <xacro:property name="camera_mass" value="0.0001" />
    <xacro:property name="servo_length" value="0.025" />
    <xacro:property name="servo_radius" value="0.015" />
    <xacro:property name="revolute" value="revolute" />
    <!-- <xacro:property name="revolute" value="fixed" /> -->


    <!-- ======================================================================== -->
    <joint name="camera_${prefix}_base_joint" type="fixed">
      <parent link="base_link"/>
      <child link="camera_${prefix}_base_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="camera_${prefix}_base_link">
      <collision>
        <origin xyz="${camera_x_offset} ${camera_y_offset * y_multiplier} ${camera_z_offset}" rpy="0 0 ${pi_2 * y_multiplier}"/>
        <geometry>
          <box size="${camera_length} ${camera_width} ${camera_height}"/>
        </geometry>
      </collision>
      <visual>
        <origin xyz="${camera_x_offset} ${camera_y_offset * y_multiplier} ${camera_z_offset}" rpy="0 0 ${pi_2 * y_multiplier}"/>
        <geometry>
          <box size="${camera_length} ${camera_width} ${camera_height/2}"/>
        </geometry>
        <material name="blue"/>
      </visual>
      <xacro:box_inertia m="${camera_mass}" w="${camera_width}" h="${camera_height}" d="${camera_length}" />
    </link>



    <!-- ======================================================================== -->

    <!-- ======================================================================== -->
    <joint name="camera_${prefix}_pan_joint" type="${revolute}">
      <parent link="camera_${prefix}_base_link"/>
      <child link="camera_${prefix}_pan_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.01"/>
      <limit lower="-${pi_2}" upper="${pi_2}" effort="1000.0" velocity="10"  />
    </joint>
    <link name="camera_${prefix}_pan_link">
      <collision>
        <origin xyz="0 0 0.01" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${servo_length}" radius="${servo_radius}"/>
        </geometry>
      </collision>
      <visual>
        <origin xyz="0 0 0.01" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${servo_length}" radius="${servo_radius}"/>
        </geometry>
        <material name="red"/>
      </visual>
      <xacro:cylinder_inertia m="0.0001" r="${servo_radius}" h="${servo_length}" />
    </link>

    <!-- ======================================================================== -->
    <joint name="camera_${prefix}_tilt_joint" type="${revolute}">
      <parent link="camera_${prefix}_pan_link"/>
      <child link="camera_${prefix}_tilt_link"/>
      <origin xyz="0 -0.023 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.01"/>
      <limit lower="-${pi_2}" upper="${pi_2}" effort="1000.0" velocity="10"  />
    </joint>
    <link name="camera_${prefix}_tilt_link">
      <collision>
        <origin xyz="0 0 0.01" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${servo_length}" radius="${servo_radius}"/>
        </geometry>
      </collision>
      <visual>
        <origin xyz="0 0 0.01" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${servo_length}" radius="${servo_radius}"/>
        </geometry>
        <material name="green"/>
      </visual>
      <xacro:cylinder_inertia m="0.0001" r="${servo_radius}" h="${servo_length}" />
    </link>
    <!-- ======================================================================== -->


    <!-- ======================================================================== -->
    <joint name="camera_${prefix}_cam_joint" type="fixed">
      <parent link="camera_${prefix}_tilt_link"/>
      <child link="camera_${prefix}_cam_link"/>
      <origin xyz="0.005 0 0" rpy="0 0 0"/>
    </joint>
    <link name="camera_${prefix}_cam_link">
      <collision>
        <origin xyz="0 0 0.01" rpy="0 ${pi_2} 0"/>
        <geometry>
          <box size="${camera_length} ${camera_width} ${camera_height}"/>
        </geometry>
      </collision>
      <visual>
        <origin xyz="0 0 0.01" rpy="0 0 0"/>
        <geometry>
          <box size="${camera_length} ${camera_width} ${camera_height/2}"/>
        </geometry>
        <material name="orange"/>
      </visual>
      <xacro:box_inertia m="${camera_mass}" w="${camera_width}" h="${camera_height}" d="${camera_length}" />
    </link>
    <!-- ======================================================================== -->



    <!-- ======================================================================== -->
    <joint name="camera_${prefix}_camlense_joint" type="fixed">
      <parent link="camera_${prefix}_cam_link"/>
      <child link="camera_${prefix}_camlense_link"/>
      <origin xyz="0.016 0.0 0.0" rpy="0 0 0"/>
    </joint>
    <link name="camera_${prefix}_camlense_link">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="0.01" radius="0.01"/>
        </geometry>
      </collision>
      <visual>
        <origin xyz="0 0 0.01" rpy="0 0 0"/>
        <geometry>
          <cylinder length="0.01" radius="0.01"/>
        </geometry>
        <material name="white"/>
      </visual>
      <xacro:box_inertia m="0.00001" w="0.0001" h="0.0001" d="0.0001" />
    </link>
    <!-- ======================================================================== -->

  </xacro:macro>

</robot>
